import type { SettingField, SettingsSchema } from './types';

export const defaultSettings: SettingsSchema = {
  windowResizable: true,
  minimizeAnimationMs: 180,
  fullscreenAnimationMs: 220,
  windowTransitionEasing: 'ease-out',
  allowOffscreenWindows: true,
  taskbarHeight: 50,
  viewportWidth: 1436,
  viewportHeight: 1080,
  viewportScaleAuto: true,
  viewportScale: 1,
  viewportScaleIntegerOnly: false,
  webcamEnabled: true,
  streamVideoUrl: '',

  iconSnapEnabled: true,
  iconGridX: 112,
  iconGridY: 100,
  iconGridOffset: 10,
  iconGridPaddingX: 16,
  iconGridPaddingY: 16,
  iconLabelLineHeight: 20,
  iconWidth: 80,
  iconHeight: 80,
  iconTaskbarHeight: 50,
  iconClampEnabled: true,
  iconClampLeft: 0,
  iconClampTop: 0,
  iconClampRightOffset: 0,
  iconClampBottomOffset: 0,
  iconDefaultX: 10,
  iconDefaultYStep: 100,
  iconDoubleClickMs: 300,

  sfxClickPath: '',
  sfxNotifyPath: '',
  sfxVolumeDefault: 0.5,
  sfxVolumeMin: 0.0,
  sfxVolumeMax: 1.0,
  sfxEnabled: true,
  crtEnabled: true,
  crtIntensity: 0.35,
};

export const settingsFields: SettingField[] = [
  { key: 'windowResizable', label: 'Window Resizable', type: 'boolean' },
  { key: 'minimizeAnimationMs', label: 'Minimize Animation (ms)', type: 'number', min: 0, max: 2000, step: 10 },
  { key: 'fullscreenAnimationMs', label: 'Fullscreen Animation (ms)', type: 'number', min: 0, max: 2000, step: 10 },
  { key: 'windowTransitionEasing', label: 'Window Transition Easing', type: 'string' },
  { key: 'allowOffscreenWindows', label: 'Allow Offscreen Windows', type: 'boolean' },
  { key: 'taskbarHeight', label: 'Taskbar Height', type: 'number', min: 20, max: 200, step: 1 },
  { key: 'viewportWidth', label: 'Viewport Width', type: 'number', min: 320, max: 1600, step: 10 },
  { key: 'viewportHeight', label: 'Viewport Height', type: 'number', min: 240, max: 1200, step: 10 },
  { key: 'webcamEnabled', label: 'Webcam Enabled', type: 'boolean' },
  { key: 'streamVideoUrl', label: 'Stream Video URL', type: 'string' },

  { key: 'iconSnapEnabled', label: 'Icon Snap Enabled', type: 'boolean' },
  { key: 'iconGridX', label: 'Icon Grid X', type: 'number', min: 20, max: 400, step: 1 },
  { key: 'iconGridY', label: 'Icon Grid Y', type: 'number', min: 20, max: 400, step: 1 },
  { key: 'iconGridOffset', label: 'Icon Grid Offset', type: 'number', min: 0, max: 50, step: 1 },
  { key: 'iconGridPaddingX', label: 'Icon Grid Padding X', type: 'number', min: 0, max: 50, step: 1 },
  { key: 'iconGridPaddingY', label: 'Icon Grid Padding Y', type: 'number', min: 0, max: 50, step: 1 },
  { key: 'iconLabelLineHeight', label: 'Icon Label Line Height', type: 'number', min: 0, max: 50, step: 1 },
  { key: 'iconWidth', label: 'Icon Width', type: 'number', min: 32, max: 200, step: 1 },
  { key: 'iconHeight', label: 'Icon Height', type: 'number', min: 32, max: 200, step: 1 },
  { key: 'iconTaskbarHeight', label: 'Icon Taskbar Height', type: 'number', min: 20, max: 200, step: 1 },
  { key: 'iconClampEnabled', label: 'Icon Clamp Enabled', type: 'boolean' },
  { key: 'iconClampLeft', label: 'Icon Clamp Left', type: 'number', min: -500, max: 500, step: 1 },
  { key: 'iconClampTop', label: 'Icon Clamp Top', type: 'number', min: -500, max: 500, step: 1 },
  { key: 'iconClampRightOffset', label: 'Icon Clamp Right Offset', type: 'number', min: -500, max: 500, step: 1 },
  { key: 'iconClampBottomOffset', label: 'Icon Clamp Bottom Offset', type: 'number', min: -500, max: 500, step: 1 },
  { key: 'iconDefaultX', label: 'Icon Default X', type: 'number', min: -500, max: 500, step: 1 },
  { key: 'iconDefaultYStep', label: 'Icon Default Y Step', type: 'number', min: 20, max: 300, step: 1 },
  { key: 'iconDoubleClickMs', label: 'Icon Double Click (ms)', type: 'number', min: 100, max: 1000, step: 10 },

  { key: 'sfxClickPath', label: 'SFX Click Path', type: 'string' },
  { key: 'sfxNotifyPath', label: 'SFX Notify Path', type: 'string' },
  { key: 'sfxVolumeDefault', label: 'SFX Default Volume', type: 'number', min: 0, max: 1, step: 0.01 },
  { key: 'sfxVolumeMin', label: 'SFX Min Volume', type: 'number', min: 0, max: 1, step: 0.01 },
  { key: 'sfxVolumeMax', label: 'SFX Max Volume', type: 'number', min: 0, max: 1, step: 0.01 },
  { key: 'sfxEnabled', label: 'SFX Enabled', type: 'boolean' },
  { key: 'crtEnabled', label: 'CRT Enabled', type: 'boolean' },
  { key: 'crtIntensity', label: 'CRT Intensity', type: 'number', min: 0, max: 1, step: 0.01 },
];

export const SETTINGS_STORAGE_KEY = 'windose_settings_v1';
